sudo: required

language: html

services:
  - docker

before_install:
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin
  - docker version
  - aws --version

script:
  - $(aws ecr get-login)
  - docker pull 928205109583.dkr.ecr.eu-west-1.amazonaws.com/symanex-site:$TRAVIS_COMMIT
  - if [ $? != 0 ]; then
    docker build -t symanex/symanex-site:$TRAVIS_COMMIT .;
    else
    docker tag 928205109583.dkr.ecr.eu-west-1.amazonaws.com/symanex-site:$TRAVIS_COMMIT symanex/symanex-site:$TRAVIS_COMMIT;
    fi
  - docker images symanex/symanex-site
  - docker run -d -p 127.0.0.1:80:80 symanex/symanex-site:$TRAVIS_COMMIT
  - docker ps -a
  - curl -sI http://127.0.0.1:80/symanex-site/ | grep "HTTP.*200.*OK"
  - docker tag symanex/symanex-site:$TRAVIS_COMMIT 928205109583.dkr.ecr.eu-west-1.amazonaws.com/symanex-site:$TRAVIS_COMMIT
  - docker push 928205109583.dkr.ecr.eu-west-1.amazonaws.com/symanex-site:$TRAVIS_COMMIT
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker tag symanex/symanex-site:$TRAVIS_COMMIT 928205109583.dkr.ecr.eu-west-1.amazonaws.com/symanex-site:travis$TRAVIS_BUILD_NUMBER;
    docker images 928205109583.dkr.ecr.eu-west-1.amazonaws.com/symanex-site:travis$TRAVIS_BUILD_NUMBER;
    docker tag symanex/symanex-site:$TRAVIS_COMMIT 928205109583.dkr.ecr.eu-west-1.amazonaws.com/symanex-site:latest;
    docker images 928205109583.dkr.ecr.eu-west-1.amazonaws.com/symanex-site:latest;
    fi
