sudo: required

language: html

services:
  - docker

before_install:
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin

script:
  - docker build -t symanex/symanex-site:$TRAVIS_BUILD_NUMBER .
  - docker images
  - docker run -d -p 127.0.0.1:80:80 symanex/symanex-site:$TRAVIS_BUILD_NUMBER
  - docker ps -a
  - curl -sI http://127.0.0.1:80/symanex-site/ | grep "HTTP.*200.*OK"
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    $(aws ecr get-login --region eu-west-1)
    docker tag symanex-site/symanex-site:$TRAVIS_BUILD_NUMBER 928205109583.dkr.ecr.eu-west-1.amazonaws.com/symanex-site:$TRAVIS_BUILD_NUMBER;
    docker images;
    docker push 928205109583.dkr.ecr.eu-west-1.amazonaws.com/symanex-site:$TRAVIS_BUILD_NUMBER;
    fi
